Console
NovelBrasil/nebi pull request #7
Opened 2024-03-11 15:52 UTC by KingTimer12

Sistema de console que cria log para alguns eventos do Discord e será utilizado para quando houver erros.

2024-03-19 15:28 UTC, wilgnert commented on src/handlers/functions/log.js
> +            const serverGuildId = `1046080828716896297`
Eu renomearia para `devServerGuildID`. Provavelmente um bom cuidado não deixar ids no código, mas na .env. Vai que existe ou alguém inventa um ataque com eles.

2024-03-19 15:34 UTC, wilgnert commented on src/handlers/functions/log.js
> +            const month = timeDate.getMonth() < 0 ? `${timeDate.getMonth() + 1}` : `0${timeDate.getMonth() + 1}`
Seria `timedate.getMonth() < 9` (9 porque mês com índice 9 é o mês 10, não precisa de 0 na frente)? E as opções estão trocadas no ternário,  você provavelmente quer adicionar o 0 se for menor.

2024-03-19 15:36 UTC, wilgnert requested changes
Veja comentários em `src/handlers/functions/log.js`

2024-03-19 15:43 UTC, KingTimer12 commented on src/handlers/functions/log.js
> +            const serverGuildId = `1046080828716896297`
porra, mas aí seria exploit mais fodido do Discord, mas tá, farei isso

2024-03-23 20:14 UTC, wilgnert approved these changes

2024-03-23 20:18 UTC, merged